# Generated by Django 2.1.5 on 2019-02-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
