# Generated by Django 2.1.5 on 2019-02-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190206_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
