# Generated by Django 2.1.5 on 2019-02-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190206_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40, null=True)),
                ('l_name', models.CharField(max_length=40, null=True)),
                ('sem', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='usr',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_Details'),
        ),
    ]
