# Generated by Django 2.1.5 on 2019-02-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190206_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='f_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='l_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='sem',
            new_name='Semester',
        ),
    ]
