# Generated by Django 2.1.5 on 2019-02-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190206_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userDetails',
        ),
        migrations.DeleteModel(
            name='user_Details',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Full_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Semester'),
        ),
    ]
